### ISSUE TITLE
one off actions

### ISSUE THREAD

**Issue by despairblue** [rackt/react-redux#100]
I wonder how I'd do one of actions.

Let's assume I have a registration form. The user types in his information and hits `send`. The server responds and says that the `username` is already taken. Now I want to focus the username input.

I can think of a couple of solutions but neither seems really elegant.

## 1
The easiest thing would probably be to save the focused input in the store and dispatch actions whenever the user focuses another input. In `componentDidUpdate` the component focuses than the correct input, but only if the currently focused input is not already the one that should be focused, otherwise the cursor would jump around while the user types. 

## 2
Another solution could be to dispatch a focus action that adds a focus entry to the store containing the element's ref-string to focus. In `componentDidUpdate` the input will then be focused and another action is dispatched that will delete this entry from the store again (it needs to be deleted, otherwise the input will be refocused every time the user changes the component, e.g. typing into another input).

Maybe I can't see the forrest for the trees, I'd appreciate any suggestion in the right direction.

Also thanks for redux, after the steep learning curve, writing components and testing logic is so much easier. It's just this thing, that I can't seem to find a good solution to.

**Comment by gnoff** [comment]
Hmm... my feeling is that neither of these is the right solution since field focus is probably better modeled as transient state. for me personally i don't imagine I'd want to be able the serialize and rehydrate/replay the sequence of field focuses. This is probably best handled outside of redux or at the very least modeled as a side effect that an action creator invokes. However this is not a settled topic for redux itself since there isn't agreement on where or how to hang side effects off of the redux ecosystem. I'm sure Dan or many others can help you out better than I but you might also have more traction in the redux repo or slack channel since the problem you bring up isn't truly react specific.

**Comment by despairblue** [comment]
I thought that this is kind of react specific, since I'd assume less declarative view kits would just listen to the store for an action.

Another idea is to pass the component instance to the action creater, the action create can then focus the correct input:

```jsx
<Button onPress={() => this.props.register(this.state, this)}>
  Or Register
</Button>
```
```javascript
function register ({username, password, email}, component) {
  return (dispatch, getState) => {
      dispatch(requestRegister())

      return fetch(API_REGISTER_URL}, {
        method: 'POST',
        headers,
        body: JSON.stringify({
          username,
          email,
          password
        })
      })
        .then(response => response.json())
        .catch(error => console.error(error.message))
        .done(json => {
          if (json.success) {
            dispatch(receiveRegister(json))
          } else if (json.data.errors.email) {
            dispatch(failRegister('Invalid email.'))
            component.refs.email.focus()
          } 
        })
    }
  }
}
```

Should I open this in the redux repo? Or I just open an issue and link to this one.

**Comment by despairblue** [comment]
After talking with @lunaris on slack, that's what we came up with: https://gist.github.com/despairblue/4ae15b40bc47d8efc2af

**Comment by gnoff** [comment]
Sure, the problem might be more tractable in other environments but what I meant was more generally is that there is often a divide between domain state and view state and while we think a lot about the domain stuff and redux is great there we don't have to and we might not want to move all view state into redux. Nothing is black and white (Atom's view toggles css classes on a timer to implement a blinking cursor and if you app is a text editor then view state like that and domain state really might be one in the same).

Your gist solution seems like a fine way to handle this since you're hanging the focus off of the async call with is already side-effect driven and not meant to be replayed etc... and won't be unless a new username check happens and you trigger a similar condition.

**Comment by despairblue** [comment]
@gnoff ok, thanks. Could you tag this as a question? Just so it's easier to find if someone else is thinking about a similar problem.
