### ISSUE TITLE
Any examples of implementing a react-redux approach with ReactTransitionGroup

### ISSUE THREAD

**Issue by duro** [rackt/react-redux#101]
I am trying to integrate a Redux based app that is using react-redux in decorator mode with ReactTransitionGroup.

The problem I'm having is that when the component, which has implemented the ReactTransitionGroup lifecycle methods, get's passed to ReactTransitionGroup, the component that is actually passed is the Connect component.

I have tried extending ReactTransitionGroup to look into WrappedComponent, but I am having trouble there. Here is the example of the extended ReactTransitionGroup that I have created:

https://gist.github.com/duro/c58d21cf3183ae01c786

With this, I get the following error:

```
Unhandled promise rejection ReferenceError: ReactTransitionChildMapping is not defined
```

Have you seen this implemented before? Any suggestions on how I could proceed forward?

**Comment by gnoff** [comment]
@duro interesting problem. I haven't dug into your gist too much but my initial intuition is that you'd be better served rendering an intermediate component between the vanilla TransitionGroup and your connected component. Is there anything in the transition lifecycle methods that actually need to be colocated with the connected component?

so instead of doing
```
render() {
  return <ReduxTransitionGroup>
                  <ConnectedComponent />
            </ReduxTransitionGroup>
}
```

you could do
```
render() {
  return <ReactTransitionGroup>
                  <TransitionWrapper> //has your componentWillAppear etc...
                      <ConnectedComponent />
                  </TransitionWrapper>
            </ReactTransitionGroup>
}
```

and TransitionWrapper would just render ```return this.props.children``` or something like that

I *think* that would work and would probably be more idiomatic and easier to test etc...

**Comment by duro** [comment]
I think this nudges me in a good direction. However, I think that the way ReactTransitionGroup works is that is wants it's direct children to be what changes. And since I am using this in react-router, my `ConnectedComponent` is a `Route` component.

So I have tried taking an approach similar to the connect decorator, which would wrap the Connected component at the class declaration level. However, I don't seem to be having much luck decorating a decorator. Here is what I have so far:

Decorator implementation:

```
import ConnectTransitionWrapper from 'client/lib/ConnectTransitionWrapper';

@ConnectTransitionWrapper()
@connect(
  state => ({people: state.people})
)
export default class About extends Component {
...
```

And my stubbed `ConnectTransitionWrapper` decorator:

```
import React, {Component} from 'react';

function getDisplayName(Component) {
  return Component.displayName || Component.name || 'Component';
}

export default function ConnectTransitionWrapper() {

  return function wrapConnectedComponent(ConnectedComponent) {

    class ConnectTransitionWrapper extends Component {

      static displayName = `ConnectTransitionWrapper(${getDisplayName(ConnectedComponent.WrappedComponent)})`;

      render() {
        console.log('ConnectTransitionWrapper rendering');
        return this.props.children;
      }
    }

  }

}
```

However, when I implement this, that `console.log never runs.

Any ideas?

**Comment by gnoff** [comment]
I think your render method should `return <ConnectedComponent {...this.props} />` but that's not the only problem you're experiencing since you say the console.log isn't being exercised. Can you confirm that your decorator is actually returning a valid React component? Does the connected component still work just without the apparent decorated component's render method?

**Comment by duro** [comment]
@gnoff I got it!!! Here is the final Decorator:

https://gist.github.com/duro/0534a9c5fe4bd8b868a8

And here is how it's implemented on a Connected component:

```
import ConnectTransitionWrapper from 'client/lib/ConnectTransitionWrapper';

@ConnectTransitionWrapper()
@connect(
  state => ({people: state.people})
)
export default class About extends Component {
...
```

**Comment by gnoff** [comment]
nice!
