### ISSUE TITLE
Wrapping components with Provider question

### ISSUE THREAD

**Issue by milosh86** [rackt/react-redux#112]
Hi,
I am having trouble to understand why the following doesn't work:

```javascript
let app = <App /> 
React.render(
<Provider store={store}>
{() => app}
</Provider>,
root
);
```
in comparison to
```javascript
React.render(
<Provider store={store}>
{() => <App />}
</Provider>,
root
);
```
it throws: `Uncaught Error: Invariant Violation: Could not find "store" in either the context or props of "Connect(App)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(App)".`

Transpiled code of both versions seems to be the same.

Use case is that I want to define routes in a different place, without wrapping it with Provider...

Thanks!

**Comment by gaearon** [comment]
Because of the way context works in React 0.13, it is important where React elements are *created*. React tracks whose `render()` is currently executing—this will be the context owner. In your case routes are created *before* `<Provider>`'s `render` executes and thus don't receive the context.

You have two options:

* Use React 0.14RC where context works just fine without a function. (e.g. you can write `<Provider><App /></Provider>` with 0.14)
* With 0.13, define your routes in a function (e.g. `createRoutes()`) in a different place and call it like `<Provider>{() => createRoutes()}</Provider>` or even `<Provider>{createRoutes}</Provider>` (note no function call—I'm passing the function so Provider can call it during its render)

**Comment by milosh86** [comment]
Great, thanks!

**Comment by jmarceli** [comment]
Crucial point is to pass the function and **not** to call it like in your example: `<Provider>{createRoutes}</Provider>`. Thanks for the solution.
