### ISSUE TITLE
Demo for 3.0.2 or complete documentation

### ISSUE THREAD

**Issue by roine** [rackt/react-redux#126]
I'm using react-redux 3.0.2 for RN and I can't find a full doc or an up to date demo about it.

**Comment by gaearon** [comment]
What doc are you looking for?

Here's the API reference: https://github.com/rackt/react-redux/blob/master/docs/api.md#api
Here's the quick start: https://github.com/rackt/react-redux/blob/master/docs/quick-start.md#quick-start
Here's a more detailed walkthrough: rackt.github.io/redux/docs/basics/UsageWithReact.html

They're not about React Native, but there is no real difference between using React Redux on web or native, other than that you need to import from `react-redux/native`.

I'm closing because we don't plan to add separate documentation for RN. If you find a good example, let us know!

**Comment by chentsulin** [comment]
@roine here is a example: https://github.com/chentsulin/react-native-counter-ios-android

**Comment by roine** [comment]
thanks guys, much appreciated.
