### ISSUE TITLE
`mapDispatchToProps` & `shouldComponentUpdate` - How do they fit together?

### ISSUE THREAD

**Issue by gsklee** [rackt/react-redux#157]
So, we're encouraged to pass actions down the component tree via `@connect`'s second parameter `mapDispatchToProps`. How does this fit with `shouldComponentUpdate()`? Actions are functions, their equality can't be easily compared.

**Comment by gaearon** [comment]
Functions can be compared just like anything else.

```
function f() { }
let g = f;

console.log(g === f); // true
```

In case of `connect()`, the second parameter is used in a special way. The bound functions are *cached*. If you don't use `ownProps` in the second function, they are bound only once. That's best for performance because their identities never change. If you do use `ownProps` in `mapDispatchToProps`, they are bound every time the props change—that's the best we can do.

**Comment by gsklee** [comment]
So, in short, if I don't use `ownProps`, `shouldComponentUpdate` will work just fine?

**Comment by gaearon** [comment]
Yes.
