### ISSUE TITLE
Getting Invariant Violation when using redux-react with Typescript/TSX

### ISSUE THREAD

**Issue by psbanka** [rackt/react-redux#162]
Now that Typescript supports JSX (with TSX), I'm excited to use React and Redux with it! However, I seem to be getting an issue when I try to wrap a React class with Provider. The code is as follows:

`Invariant Violation: onlyChild must be passed a children with exactly one child.`

The files I'm using are in [This gist](https://gist.github.com/psbanka/1b7df3850f8830b89873)

As I dug into the redux-react code, the error is being generated from this stanza:

```
  Provider.prototype.render = function render() {
    var children = this.props.children;

    return _react.Children.only(children);
  };
```
And it turned out that `this.props.children` was a *function* which returned a React element rather than a React element itself? I don't know how this could be occurring. Any suggestions would be appreciated!

**Comment by gaearon** [comment]
The code you're running is for Redux React 3.x.
The version you're using is 4.x.

4.x no longer allows function-as-a-child for `<Provider>` because the only reason we had it is for React 0.13 compat, and now we require React 0.14.

https://github.com/rackt/react-redux/releases/tag/v4.0.0

You need to change

```js
React.render(
    <Provider store={store}>
        {() => <Main />}
    </Provider>, document.body);
```

to

```js
ReactDOM.render(
    <Provider store={store}>
        <Main />
    </Provider>, document.body);
```

**Comment by psbanka** [comment]
Thanks for the quick answer!

**Comment by paramsingh88** [comment]
I'm facing the same issue. Can't solve it!!

**Comment by dannypule** [comment]
@paramsingh88 can you paste your code? I was getting this same error message but that's because I put a comment between the <Provider></Provider> tags.

**FROM**
`render( // React render
  <Provider store={store}> {/* Provider function is a container component from redux */}
    <Router history={browserHistory} routes={routes} />
  </Provider>, 
  document.getElementById('app') // root element of react app
);`

**TO**
`render( // React render
  <Provider store={store}>
    <Router history={browserHistory} routes={routes} />
  </Provider>, 
  document.getElementById('app') // root element of react app
);`
