### ISSUE TITLE
React Native: Invalid prop children supplied to Provider

### ISSUE THREAD

**Issue by feifanzhou** [rackt/react-redux#200]
var App = React.createClass({
      render() {
        return <Text style={styles.paddingTop}>App</Text>
      }
    });
    
    const Main = React.createClass({
      render() {
        return (
          <Provider store={store}>
            <App />
          </Provider>
        )
      }
    })    

This throws `Error: Invariant Violation: onlyChild must be passed a children with exactly one child`. 

In `Provider.js`, if I return `children` directly rather than returning `_react.Children.only(children)`, the component _renders fine_, although it still triggers `Warning: Failed propType: Invalid prop `children` supplied to `Provider`, expected a single ReactElement.`

**Comment by gaearon** [comment]
What versions of React Native and React Redux are you running?
Are you sure there’s no `node_modules/react` that got installed by mistake?

Note that React Native requires React Redux 3.x until https://github.com/facebook/react-native/issues/2985 is solved, and that you have to import both `Provider` and `connect` from `react-redux/native` instead of `react-redux`. After https://github.com/facebook/react-native/issues/2985 is fixed, you will be able to use React Redux 4.x (latest) and import from `react-redux` directly.
