### ISSUE TITLE
Can Provider implementation be different? Just a thought.

### ISSUE THREAD

**Issue by prashanth1509** [rackt/react-redux#201]
Providers use react's context api to inject store into the components. But we can achieve something similar by reimplementing Provider component in a safer way (kindof pseudocode).

Example,
```js
export class Provider extends React.Component {
    render(){
        return <div>{this.renderChildren(this.props.children)}</div>;
    }
    renderChildren(children) {
        return React.Children.map(children, (child) => {
            if ( Object.getOwnPropertyNames(child.type).indexOf('childContextTypes') === -1 ){
                throw new Error(
                    `Children of Provider module should set childContextTypes property`
                );
            }
            return React.addons.cloneWithProps(child, {store: this.props.store});
        });
    }
}
```
and usage would be like,

All the smart (sometimes dumb) components that require store should be surrounded with Provider component.

```js
<Provider store={store}><ComponentA/></Provider>
<Provider store={store}><ComponentB/></Provider>
```

Since we enforce childContextTypes to be set by those child components, its future proof in a way that if react stabilizes context api all the components can easily migrate.

**Comment by gnoff** [comment]
The point of `Provider` today is to mount the store in a context so that components at any tier of the Component tree can `connect` to it and select the state that is relevant for themselves. In your re-imagining of the Provider it seems you want to be able to supply the store to arbitrary components but this isn't the intent of the react-redux bindings. If you do this then you have to manually subscribe to store updates etc...

I may be misinterpreting your suggestion or intention about what this new way accomplishes but I think you're focusing on the least valuable part of the react-redux library.

In fact if you don't like the use of context you can just pass store as a prop through your component tree and supply it to components using `connect` (this is actually a bad idea of anything of significant size/complexity, perfect for tests though) or if you don't care about Universal Apps and the ability to render on the server and singletons aren't a problem you can just sideload the store as a prop (require it in each component that is being connected and pass to said component).

All that said, there isn't anything wrong in my opinion using context. It's even documented now https://facebook.github.io/react/docs/context.html

Even if the API changes the library can and will change along with it.

Am I missing something perhaps?

**Comment by gaearon** [comment]
The main use case of `<Provider>` is to give `store` to all connected components *no matter how deep they are*. Unless we do this, introducing a new container (= smart) component somewhere inside a presentational (= dumb) component suddenly means we have to thread `store` as a prop all the way down there. This plumbing is not convenient.

I compare these approaches in my Egghead Redux lessons:

* [Passing the Store Down Explicitly via Props](https://egghead.io/lessons/javascript-redux-passing-the-store-down-explicitly-via-props?series=getting-started-with-redux)
* [Passing the Store Down Implicitly via Context](https://egghead.io/lessons/javascript-redux-passing-the-store-down-implicitly-via-context?series=getting-started-with-redux)
* [Passing the Store Down with `<Provider>` from React Redux](https://egghead.io/lessons/javascript-redux-passing-the-store-down-with-provider-from-react-redux?series=getting-started-with-redux)

They are free, so please consult them to follow my thought process!

>its future proof in a way that if react stabilizes context api all the components can easily migrate.

Using React Redux is already future proof because it hides context API from you. If context API changes we'll just update React Redux, and as long as you use `connect()` and `<Provider>` you'll never know.
