### ISSUE TITLE
Using systemjs-hot-reloader

### ISSUE THREAD

**Issue by vsviridov** [rackt/react-redux#223]
Not strictly an issue, but SO is silent on the matter.

I use [JSPM](http://jspm.io) instead of WebPack, and recently wired up the [capaj/systemjs-hot-reloader](https://github.com/capaj/systemjs-hot-reloader) module. However when my components are reloaded I get the `<Provider> does not support changing 'store' on the fly.` error message.

It looks like I need to undertake additional steps to get it goin...
Any suggestions?

**Comment by gaearon** [comment]
I don't know about JSPM but you should be careful not to re-evaluate creation of your store. Some hot reloading solutions (Webpack, Browserify HMR) let you control what gets re-evaluated and what doesn't.

If systemjs-hot-reloader always re-executed *everything* you might be better off keeping your store in a global variable on the window so that it isn't created twice.

**Comment by allochi** [comment]
@vsviridov I had the same situation :D, thanks to @gaearon advice, this works for me

```js
import {createStore} from 'redux';
import rootReducer from './reducers';

export default function configureStore(initialState) {
	if (System.trace) {
		if (window.store == undefined) {
			window.store = createStore(rootReducer, initialState);
			window.store.replaceReducer(rootReducer);
		}
		return window.store;
	} else {
		return createStore(rootReducer, initialState);
	}
};
```

**Comment by vsviridov** [comment]
@allochi Thanks. That cleared things up.
