### ISSUE TITLE
Predicate function for updating component.  

### ISSUE THREAD

**Issue by gacosta89** [rackt/react-redux#235]
It would be nice to have an optional predicate function to pass to the connect function, so we can do ~~the usual~~ further immutable data optimizations.

Something like this:
````
function connect(mapStateToProps, mapDispatchToProps, mergeProps, updateComponent, options = {})
....
const defaultUpdateComponent = (prevStoreState, storeState) =>  prevStoreState !== storeState;
const finalUpdateComponent = updateComponent || defaultUpdateComponent;
````
then in handleChange:
````
handleChange() {
....
  if (!pure || finalUpdateComponent(prevStoreState, storeState)) {
       this.hasStoreStateChanged = true
     this.setState({ storeState })
  }
}
````

P.D.: Happy New Year!

**Comment by DeadMG** [comment]
I've also noticed that for your own props, shallowEqual is used, but for the store props, it's strict object identity only. This somewhat concerns me as it seems that it would be slightly tricky to always preserve the exact object instance just to optimize the comparison a little bit which we may not even need.

It would be nice if we could supply our own comparison or even just use shallowEqual.

**Comment by gaearon** [comment]
There is a possibility that we’ll make `arePropsEqual` configurable (https://github.com/rackt/react-redux/pull/183) but I don't think we want to provide any more customization.

Just because that `setState()` call happens doesn't mean your inner component will actually get updated. We have a bunch of additional optimizations (in `shouldComponentUpdate()` and `render()`) that will try very hard to prevent renders if **the slice of state you're actually interested in** (as determined by `mapStateToProps()` you supplied) has not changed. We have a whole bunch of tests proving that those optimizations work and renders are only performed when absolutely necessary.

>I've also noticed that for your own props, shallowEqual is used, but for the store props, it's strict object identity only. 

This is incorrect. `shallowEqual` is used to compare all props, whether derived from parent props, or store. Please see [here](https://github.com/rackt/react-redux/blob/4fca3cbc736b7462de65f589d3b0fdab0cb7a495/src/components/connect.js#L101), [here](https://github.com/rackt/react-redux/blob/4fca3cbc736b7462de65f589d3b0fdab0cb7a495/src/components/connect.js#L111), and [here](https://github.com/rackt/react-redux/blob/4fca3cbc736b7462de65f589d3b0fdab0cb7a495/src/components/connect.js#L150).

>This somewhat concerns me as it seems that it would be slightly tricky to always preserve the exact object instance just to optimize the comparison a little bit which we may not even need- or in other words, data sharing between immutable instances becomes mandatory, rather than a nice optimization.

Unfortunately I don't understand the problem you're describing at all. :-( Maybe some code would help?
