### ISSUE TITLE
Pure-render-debug mode

### ISSUE THREAD

**Issue by tmcw** [rackt/react-redux#273]
I've been using react-redux with a few lines of hacks to narrow down performance issues in my application: the console output looks like:

<img width="266" alt="2016-01-27 at 4 50 pm" src="https://cloud.githubusercontent.com/assets/32314/12629578/7c845eba-c516-11e5-99d6-4c2fca5eb28d.png">

This identifies which props in which connect() calls cause re-renders. This has been super useful, and I'd like everyone on my team to have the same ability. Would this be something contributable to react-redux itself, or is there a potential way to implement it as an add-on? It is hooking into shallowEquals and the shouldComponentUpdate method to identify culprits.

**Comment by gaearon** [comment]
I think this is best served on generic React tooling level. There are some projects like https://github.com/spredfast/react-transform-render-visualizer. There is also intent (AFAIK) to get something similar into the official React DevTools extension.

**Comment by jonaskello** [comment]
@tmcw Do you have your branch somewhere on github? I am also facing problems with re-render and finding it is very hard to tell why a connected component re-renders. Currently I am hooking mergeProps(), saving the previous props and then doing shallowEquals with them. But all the props are the same so something else is going on but I have no clue what since the wrapper component does not output any debugging info.

The demo of react-transform-render-visualizer sure seems nice but in a large project with complex state I don't think it will work well. For example I have immutablejs state etc. It also requires your components to be classes but most of mine are stateless functions. In addition it requires babel. 

Some other solution to seeing why a connected component re-renders would be really nice. Maybe the wrapper component could take an option that turns logging on?
