### ISSUE TITLE
Semi Unexpected Behaviour with Connect

### ISSUE THREAD

**Issue by thomasdavis** [rackt/react-redux#280]
Was debugging a component for a long time trying to figure out why `this.props.dispatch` wasn't available.

Turns out I had an empty object in my `connect` decorator;

```
@connect(mapStateToProps, {})
```

Once I removed the empty object, `this.props.dispatch` was available. 

Was hoping somebody could explain why and if this should be the case.

**Comment by gaearon** [comment]
This is not the relevant repository. You are probably asking about [React Redux](https://github.com/rackt/react-redux).

The reason is that second argument to `connect()` can be either a function or an object, per its [documentation](https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options). If it is a function, it is expected to return the props to inject into the component. If it is an object, it will assume the values in that object are action creators, and inject bound action creators. The only case where you get just `{ dispatch }` is when you don’t specify `mapDispatchToProps` at all.
