### ISSUE TITLE
Provider component is not intuitive for passing props

### ISSUE THREAD

**Issue by jiyinyiyong** [rackt/react-redux#68]
Previously discussed on Twitter: https://twitter.com/dan_abramov/status/635441125013200896

Related code:
https://github.com/jackielii/simplest-redux-example/blob/master/index.js#L56

```js
React.render(
  <Provider store={store}>
    {() => <App />}
  </Provider>,
  document.getElementById('root')
);
```

In order to pass the props, we need one more file to bind the props:

![import copy](https://cloud.githubusercontent.com/assets/449224/9428456/433bb2d0-49e1-11e5-830b-0f02e391e73a.png)

**Comment by gaearon** [comment]
I'm not really sure what props you have troubles passing. `Root` and `Provider` are just plumbing: they look intimidating in a tiny app, but you only need to declare them once.

What problems do you have, after `Root` is declared and uses `Provider`? Let's imagine your app starts at `CounterApp`.

**Comment by jiyinyiyong** [comment]
I'm not reporting it as a bug. It may be an improvement or something.

**Comment by gaearon** [comment]
I'm not saying I think you're reporting it as a bug :-).
I'm just trying to understand what could be improved. Can you suggest a different API?

**Comment by gaearon** [comment]
To clarify, `<Provider>` is not there to pass props. It's there to make `connect()` work no matter how deep it is in your app hierarchy. It uses undocumented React "context" feature to do that.

**Comment by jiyinyiyong** [comment]
I'm giving up. I just thought it can be simpler(like passing props directly), without understanding the implementation details. And probably I don't understand the true purpose behind `<Provider>`

And I turned my ideas into a "Redux clone for learning purpose" at https://github.com/mvc-works/actions-recorder (use `gulp script` or `npm i actions-recorder` to get JavaScript version if you need).

**Comment by gaearon** [comment]
>And probably I don't understand the true purpose behind <Provider>

The purpose is to expose `store` on the React context. As I said, context is [undocumented React feature](http://www.youtube.com/watch?v=H7vlH-wntD4) so I understand the confusion.

Without `<Provider>` or something similar, you can't `connect()` components somewhere deep in the hierarchy. `connect()` needs to read `store` somehow so it can subscribe to it. `<Provider>` puts `store` in React context so `connect()` can read it from there. If there was no provider, you'd have to either

a) pass the `store` down via props through you whole application (very verbose);
b) export a singleton `store` and let all components use it, but this doesn't work for apps rendering on server, because they want to have a `store` instance per request.

**Comment by oliviertassinari** [comment]
> And probably I don't understand the true purpose behind

Same for me. Now, I understand, thanks.

**Comment by jiyinyiyong** [comment]
It makes sense. We even used a `listenTo` mixin to to the job and it's so much code.

Personaly I still prefer the verbose way since it doesn't intrduce new terms or concepts. I can see the "very verbose" way in my own solution:

```js
React.render(Page({
  store: initial,
  records: Immutable.List(),
  pointer: -1
}), document.body);
recorder.subscribe(function (store, records, pointer) {
  return React.render(Page({
    store: store,
    records: records,
    pointer: pointer
  }), document.body);
});
```

**Comment by gaearon** [comment]
Yes, and also always tendering from the top will be slower.

**Comment by jiyinyiyong** [comment]
Did you mean `React.render` is slower than `Component.setState()`?

**Comment by gaearon** [comment]
Yes, it's faster to `setState` in the middle of the view hierarchy than `React.render` at the top because this saves React work of figuring out that other components have not changed.

If most of your components [implement `shouldComponentUpdate`](https://facebook.github.io/react/docs/advanced-performance.html) it's not such a problem, but it's still more performant to use `setState` in the middle (via `connect()` or a custom helper—but again, `connect` is optimized so you should probably use it).

**Comment by jiyinyiyong** [comment]
I prefer Immutable data in such cases :)

**Comment by gaearon** [comment]
Immutable doesn't solve this problem. React has to reconcile the tree, whether you use Immutable or something else.

**Comment by jiyinyiyong** [comment]
Fine.
