### ISSUE TITLE
Browser bundle

### ISSUE THREAD

**Issue by vipulnsward** [rackt/react-redux#76]
Similar to https://cdnjs.com/libraries/redux , it would be great to have react-redux wrapped in a bundle.

**Comment by gnoff** [comment]
that's up to cdnjs

this is how you request they add a lib apparently (just googled it myself)
https://goo.gl/EfDJx9

**Comment by vipulnsward** [comment]
@gnoff The issue was more around distributable browser bundle that cdnjs.
Is there a way currently to use it, that I am missing?

**Comment by gnoff** [comment]
yup,

npm install react-redux
check node_modules/react-redux/dist/react-redux.js and react-redux.min.js

**Comment by gaearon** [comment]
Let's reopen until we put `react-redux` on cdnjs ourselves.
Then we can point people to it.

**Comment by hummlas** [comment]
I'm working on a project where Bower and RequireJS is used, and since I couldn't find a minified version (or even an ES5-transpiled one) I forked this repo and removed the `dist` folder from `.gitignore` after building the bundles and created an new tag that is v3.0.1.1 which includes the `dist` folder.

Fork can be found at https://github.com/hummlas/react-redux

It can be installed via Bower with:
`bower install react-redux=https://github.com/hummlas/react-redux.git#v3.0.1.1 --save`

**Comment by gaearon** [comment]
If you can prepare a PR for cdnjs that would be rad.
This way, you can point Bower to cdnjs file.

**Comment by gaearon** [comment]
Here is an example of how I did it for redux: https://github.com/cdnjs/cdnjs/pull/5371

**Comment by gaearon** [comment]
It's going to be on cdnjs soon: https://github.com/cdnjs/cdnjs/pull/5980

**Comment by gaearon** [comment]
React Redux is now available on cdnjs: https://cdnjs.com/libraries/react-redux
