### ISSUE TITLE
Add connect() example: () => ({})

### ISSUE THREAD

**Issue by preflight** [rackt/react-redux#94]
I came across an interesting [implementation](https://github.com/voronianski/flux-comparison/blob/master/redux/js/components/App.jsx#L17) of `connect()` in Dmitri Voronianski's [Flux Comparison](https://github.com/voronianski/flux-comparison) repo and thought it might make a nice addition to the docs:

`export default connect(() => ({}))(App);`

If I'm understanding it correctly, this would subscribe the component to the Redux store and pass an empty object for props. This component is used to render two containers but lets them to pull in what they need vs. passing it to them as props. I deduce that if nothing were passed to `connect()`, one container wouldn't see things that occurred in the other, but I'm not certain.

**Comment by gnoff** [comment]
@preflight the `() => ({})` parameter is actually not necessary in this case since that is the default mapper so using `connect()(App)` actually gets you the same functionality. That said there isn't much use in subscribing to the redux store if you don't provide a mapper to grab some state. The CartContainer and ProductsContainer which are both connected will work just fine with an unconnected parent App. If anything it triggers unnecessary re-renders though in this simple example it's irrelevant

**Comment by preflight** [comment]
Excellent - thanks for clarifying

**Comment by gnoff** [comment]
no problem
